### ISSUE TITLE
Not working on DNN 9.4+ and 2sxc 10.20+

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/app-owl-slider#2]
Attempted to install about 5 apps at once (I doubt multiple is a factor since re-install solo had the same result).
 
2sxcApp_ImageSlider_01.00.02.zip

The install appeared to go okay, but afterwards, when you try to use it, the Content-Type "Image" is there, but the View is missing. The physical file is there, /2sxc/OWL ImageSlider/_ImageSlider.cshtml, the the View (Entity) is missing.

When you add the app in to a pane, you select the Owl Imageslider, then it switches to Views and it just spins/reloads forever.
 
Also note, using another DNN/2sxc instance for reference, I was able to get it working by manually adding the view with the same settings.

**Comment by iJungleboy** [comment]
I'll check, thx.

**Comment by iJungleboy** [comment]
Could you check our latest 2.0.3 release https://github.com/2sic/app-owl-slider/releases/tag/02.00.03 and tell us if it worked? I just tested it, should work :)

**Comment by jeremy-farrance** [comment]
Yes, that did work. Only minor issue now is that it seems to have some elements showing up in another language.

![image](https://user-images.githubusercontent.com/653301/69749964-3df7fd00-1111-11ea-96b5-834a41f7b6e8.png)

**Comment by iJungleboy** [comment]
thanks for this, we'll see that we can fix it within the next few days. I created a separate issue #3
